/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  BlockType,  ClassOutline,  Coverage,  DocumentAnalysis,  LessonBlockRaw,  LessonOutline,  ModuleOutline,  ModuleQuiz,  QuizQuestion,  StepItem,  TermPair,  Topic,  WrittenLesson } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ClassOutline {
      modules: ModuleOutline[]
    }
    export interface DocumentAnalysis {
      summary?: string | null
      topics: Topic[]
      prerequisites: string[]
      suggested_module_count?: number | null
      warnings: string[]
    }
    export interface LessonBlockRaw {
      type?: types.BlockType | null
      markdown?: string | null
      variant?: string | null
      title?: string | null
      terms?: TermPair[] | null
      headers?: string[] | null
      rows?: string[][] | null
      steps?: StepItem[] | null
      points?: string[] | null
      source?: string | null
      caption?: string | null
      question?: string | null
      options?: string[] | null
      correct_index?: number | null
      explanation?: string | null
    }
    export interface LessonOutline {
      title?: string | null
      objectives: string[]
      chunk_refs: number[]
      estimated_minutes?: number | null
    }
    export interface ModuleOutline {
      title?: string | null
      description?: string | null
      lessons: LessonOutline[]
    }
    export interface ModuleQuiz {
      title?: string | null
      questions: QuizQuestion[]
    }
    export interface QuizQuestion {
      question?: string | null
      options: string[]
      correct_index?: number | null
    }
    export interface StepItem {
      title?: string | null
      markdown?: string | null
    }
    export interface TermPair {
      term?: string | null
      definition?: string | null
    }
    export interface Topic {
      title?: string | null
      coverage?: types.Coverage | null
      needs_expansion?: boolean | null
      notes?: string | null
    }
    export interface WrittenLesson {
      blocks: LessonBlockRaw[]
      key_terms: string[]
    }
}