/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum BlockType {
  PROSE = "PROSE",
  CALLOUT = "CALLOUT",
  KEY_TERMS = "KEY_TERMS",
  COMPARISON = "COMPARISON",
  MERMAID = "MERMAID",
  STEPS = "STEPS",
  INLINE_CHECK = "INLINE_CHECK",
  WIDGET = "WIDGET",
  RECAP = "RECAP",
}

export enum Coverage {
  EXPLAINED = "EXPLAINED",
  PARTIAL = "PARTIAL",
  MENTIONED = "MENTIONED",
}

export interface ClassOutline {
  modules: ModuleOutline[]
  
}

export interface DocumentAnalysis {
  summary: string
  topics: Topic[]
  prerequisites: string[]
  suggested_module_count: number
  warnings: string[]
  
}

export interface LessonBlockRaw {
  type: BlockType
  markdown?: string | null
  variant?: string | null
  title?: string | null
  terms?: TermPair[] | null
  headers?: string[] | null
  rows?: string[][] | null
  steps?: StepItem[] | null
  points?: string[] | null
  source?: string | null
  caption?: string | null
  question?: string | null
  options?: string[] | null
  correct_index?: number | null
  explanation?: string | null
  html?: string | null
  brief?: string | null
  fallback_markdown?: string | null
  
}

export interface LessonOutline {
  title: string
  objectives: string[]
  chunk_refs: number[]
  estimated_minutes: number
  
}

export interface ModuleOutline {
  title: string
  description: string
  lessons: LessonOutline[]
  
}

export interface ModuleQuiz {
  title?: string | null
  questions: QuizQuestion[]
  
}

export interface QuizQuestion {
  question: string
  options: string[]
  correct_index: number
  
}

export interface StepItem {
  title: string
  markdown: string
  
}

export interface TermPair {
  term: string
  definition: string
  
}

export interface Topic {
  title: string
  coverage: Coverage
  needs_expansion: boolean
  notes: string
  
}

export interface WrittenLesson {
  blocks: LessonBlockRaw[]
  key_terms: string[]
  
}
