/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals.js"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    ClassOutline: ClassViewer<'ClassOutline', "modules">;
    
    DocumentAnalysis: ClassViewer<'DocumentAnalysis', "summary" | "topics" | "prerequisites" | "suggested_module_count" | "warnings">;
    
    LessonBlockRaw: ClassViewer<'LessonBlockRaw', "type" | "markdown" | "variant" | "title" | "terms" | "headers" | "rows" | "steps" | "points" | "source" | "caption" | "question" | "options" | "correct_index" | "explanation">;
    
    LessonOutline: ClassViewer<'LessonOutline', "title" | "objectives" | "chunk_refs" | "estimated_minutes">;
    
    ModuleOutline: ClassViewer<'ModuleOutline', "title" | "description" | "lessons">;
    
    ModuleQuiz: ClassViewer<'ModuleQuiz', "title" | "questions">;
    
    QuizQuestion: ClassViewer<'QuizQuestion', "question" | "options" | "correct_index">;
    
    StepItem: ClassViewer<'StepItem', "title" | "markdown">;
    
    TermPair: ClassViewer<'TermPair', "term" | "definition">;
    
    Topic: ClassViewer<'Topic', "title" | "coverage" | "needs_expansion" | "notes">;
    
    WrittenLesson: ClassViewer<'WrittenLesson', "blocks" | "key_terms">;
    
    
    BlockType: EnumViewer<'BlockType', "PROSE" | "CALLOUT" | "KEY_TERMS" | "COMPARISON" | "MERMAID" | "STEPS" | "INLINE_CHECK" | "RECAP">;
    
    Coverage: EnumViewer<'Coverage', "EXPLAINED" | "PARTIAL" | "MENTIONED">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "ClassOutline","DocumentAnalysis","LessonBlockRaw","LessonOutline","ModuleOutline","ModuleQuiz","QuizQuestion","StepItem","TermPair","Topic","WrittenLesson",
          ]),
          enums: new Set([
            "BlockType","Coverage",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.ClassOutline = this.tb.classViewer("ClassOutline", [
          "modules",
        ]);
        
        this.DocumentAnalysis = this.tb.classViewer("DocumentAnalysis", [
          "summary","topics","prerequisites","suggested_module_count","warnings",
        ]);
        
        this.LessonBlockRaw = this.tb.classViewer("LessonBlockRaw", [
          "type","markdown","variant","title","terms","headers","rows","steps","points","source","caption","question","options","correct_index","explanation",
        ]);
        
        this.LessonOutline = this.tb.classViewer("LessonOutline", [
          "title","objectives","chunk_refs","estimated_minutes",
        ]);
        
        this.ModuleOutline = this.tb.classViewer("ModuleOutline", [
          "title","description","lessons",
        ]);
        
        this.ModuleQuiz = this.tb.classViewer("ModuleQuiz", [
          "title","questions",
        ]);
        
        this.QuizQuestion = this.tb.classViewer("QuizQuestion", [
          "question","options","correct_index",
        ]);
        
        this.StepItem = this.tb.classViewer("StepItem", [
          "title","markdown",
        ]);
        
        this.TermPair = this.tb.classViewer("TermPair", [
          "term","definition",
        ]);
        
        this.Topic = this.tb.classViewer("Topic", [
          "title","coverage","needs_expansion","notes",
        ]);
        
        this.WrittenLesson = this.tb.classViewer("WrittenLesson", [
          "blocks","key_terms",
        ]);
        
        
        this.BlockType = this.tb.enumViewer("BlockType", [
          "PROSE","CALLOUT","KEY_TERMS","COMPARISON","MERMAID","STEPS","INLINE_CHECK","RECAP",
        ]);
        
        this.Coverage = this.tb.enumViewer("Coverage", [
          "EXPLAINED","PARTIAL","MENTIONED",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}